import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FFFDF7",
    paddingHorizontal: 20,
    paddingTop: 60,
  },
  contents: {
    width: "90%",
    marginLeft: "auto",
    marginRight: "auto",
  },
  headerContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 16,
  },
  headerCenter: {
    flex: 1,
    alignItems: "center",
  },
  headerTitle: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
  },
  profileSection: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: "10%",
    marginBottom: "10%",
  },
  avatarPlaceholder: {
    width: 70,
    height: 70,
    borderRadius: 30,
    marginRight: 12,
    alignItems: "center",
    position: "relative",
    justifyContent: "center",
  },
  avatarSvg: {
    width: 80,
    height: 80,
    elevation: 2,
    position: "absolute",
    zIndex: 2,
    top: 10,
    left: 10,
  },
  profileText: {
    flex: 1,
  },
  username: {
    fontSize: 16,
    fontWeight: "bold",
  },
  usernameInput: {
    fontSize: 16,
    fontWeight: "bold",
    borderBottomWidth: 1,
    borderColor: "#ccc",
    paddingVertical: 2,
  },
  editButton: {
    marginTop: 4,
  },
  subtext: {
    fontSize: 12,
    color: "#666",
  },
  menuItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 20,
    borderBottomWidth: 1,
    borderColor: "#ccc",
  },
  menuTitle: {
    fontSize: 16,
    fontWeight: "bold",
  },
  birthInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 14,
    position: "relative",
    borderTopWidth: 1,
    borderColor: "#ccc",
    paddingTop: "10%",
  },
  genderInfoRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 16,
    paddingBottom: "10%",
    position: "relative",
    borderBottomWidth: 1,
    borderColor: "#ccc",
  },
  infoLabel: {
    fontSize: 16,
    fontWeight: "bold",
    color: "black",
  },
  infoValue: {
    fontSize: 14,
    color: "#000",
  },
  logoutSection: {
    // 절대 위치로 하단에 고정
    position: "absolute",
    bottom: "10%",
    left: 0,
    right: 0,
    alignItems: "center",
    flexDirection: "row",
    justifyContent: "center",
  },
  logoutText: {
    fontSize: 14,
    color: "#666",
    marginHorizontal: 4,
  },
  divider: {
    height: 1,
    backgroundColor: "#ccc",
    marginVertical: 5,
    zIndex: -1,
  },
  arrow: {
    fontSize: 18,
    color: "#666",
  },
  genderDropdown: {
    position: "absolute",
    top: 40,
    right: 0,
    backgroundColor: "#fff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ccc",
    overflow: "hidden",
    width: 120,
    zIndex: 10,
    elevation: 10,
  },
  dropdownItem: {
    padding: 10,
    fontSize: 14,
    color: "#333",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    justifyContent: "center",
    alignItems: "center",
  },
  calendarContainer: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 16,
    width: "90%",
  },
  modalCloseButton: {
    marginTop: 10,
    alignSelf: "flex-end",
  },
  modalCloseText: {
    fontSize: 16,
    color: "#007AFF",
  },
  calendar: {
    paddingBottom: 20,
    borderWidth: 1,
    borderColor: "#E9E9E9",
    borderRadius: 20,
  },
  loadingText: {
    fontSize: 18,
    textAlign: "center",
    marginTop: 50,
    color: "#666",
  },
});
